### ISSUE TITLE
[MUSIC ISSUE] Overlapping tracks

### ISSUE THREAD

**Issue by Junl424** [Twisted-BrainZ/AST-Hero#12]
When the final boss is defeated, a new music starts, more chill aka victory song.
Then the previous battle music come back until I validate my score and go to the credits or menu.
It seems to overlap the 2 songs but I'm not sure.

1. Finish the last boss

**Expected behavior**
To keep the final song until back to the menu or to the credits

**Relevant Hardware Information: (remove what is not relevant or correct the information)**
 - OS: Windoes 11
 - Tower
 - Ram amount: 8GB&More

**Additional context**
Difficulty selected: normal

**Comment by Maxwelljones** [comment]
Resolved in build 1.0.1
